import React, { useState } from 'react';

export default function TriFormatResourceHub({ topic, classId, subjectId, topicId, onOpenFlashcards }) {
  const [activeMode, setActiveMode] = useState('all'); // 'all' | 'watch' | 'read' | 'revise' | 'listen'
  const [isPlayingAudio, setIsPlayingAudio] = useState(false);

  function handleSpeech() {
    if (!('speechSynthesis' in window)) {
      alert('Text-to-speech is not supported in your browser.');
      return;
    }

    if (isPlayingAudio) {
      window.speechSynthesis.cancel();
      setIsPlayingAudio(false);
      return;
    }

    const textToRead = `${topic.title}. ${topic.definition || ''}. Key points: ${topic.qa?.map(q => q.q).join('. ') || ''}`;
    const utterance = new SpeechSynthesisUtterance(textToRead);
    utterance.rate = 0.95;
    utterance.pitch = 1.0;
    utterance.onend = () => setIsPlayingAudio(false);
    utterance.onerror = () => setIsPlayingAudio(false);

    window.speechSynthesis.speak(utterance);
    setIsPlayingAudio(true);
  }

  function handleDownloadMindMap() {
    const content = `====================================================
ONLINESTUDYHUB 1-PAGE MIND MAP & CHEAT SHEET
Topic: ${topic.title} (${classId.toUpperCase()} - ${subjectId.toUpperCase()})
====================================================

📌 DEFINITION & GOVERNING PRINCIPLE:
${topic.definition || 'Key concept principles and relations.'}

💡 HIGH-YIELD FORMULAS & LAWS:
- Governing Relation: Check SI unit consistency.
- Standard Form: Verify parameter dimensions.

📝 PYQ ACTIVE RECALL QUESTIONS:
${topic.qa?.map((q, idx) => `${idx + 1}. Q: ${q.q}\n   A: ${q.a}\n`).join('\n') || ''}

====================================================
Generated by OnlineStudyHub — https://onlinestudyhub.com
`;

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${topicId}-mindmap-cheatsheet.txt`;
    link.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div style={{ background: 'linear-gradient(135deg, #0f172a, #1e1b4b)', border: '1.5px solid rgba(255,255,255,0.15)', borderRadius: 20, padding: '1.25rem', marginBottom: '2rem', color: '#fff', boxShadow: '0 10px 30px rgba(0,0,0,0.25)' }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '1rem', marginBottom: '1rem', borderBottom: '1px solid rgba(255,255,255,0.1)', paddingBottom: '.75rem' }}>
        <div>
          <div style={{ fontSize: '.72rem', fontWeight: 900, color: '#38bdf8', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
            ⚡ Seamless Multi-Format Learning Hub
          </div>
          <h3 style={{ fontFamily: 'Nunito', fontWeight: 900, color: '#fff', fontSize: '1.1rem', margin: '.2rem 0 0' }}>
            Choose How You Learn Best: Watch, Read, Revise, or Listen
          </h3>
        </div>

        {/* Audio Summary Listener CTA */}
        <button
          onClick={handleSpeech}
          style={{
            background: isPlayingAudio ? '#ef4444' : 'linear-gradient(135deg, #10b981, #059669)',
            color: '#fff',
            border: 'none',
            borderRadius: 12,
            padding: '.55rem 1.1rem',
            fontSize: '.82rem',
            fontWeight: 900,
            cursor: 'pointer',
            display: 'flex',
            alignItems: 'center',
            gap: '.4rem',
            boxShadow: '0 4px 14px rgba(16,185,129,0.35)',
            transition: 'all 0.2s'
          }}
        >
          {isPlayingAudio ? '⏹️ Stop Audio Summary' : '🎧 Listen 2-Min Audio Summary'}
        </button>
      </div>

      {/* Tri-Format Mode Selector Buttons */}
      <div style={{ display: 'flex', gap: '.5rem', flexWrap: 'wrap' }}>
        <button
          onClick={() => setActiveMode('all')}
          style={{
            flex: 1,
            minWidth: 120,
            padding: '.65rem .85rem',
            border: 'none',
            borderRadius: 12,
            fontWeight: 900,
            fontSize: '.83rem',
            cursor: 'pointer',
            background: activeMode === 'all' ? 'linear-gradient(135deg, #6366f1, #4f46e5)' : 'rgba(255,255,255,0.08)',
            color: '#fff',
            transition: 'all 0.2s'
          }}
        >
          🌟 All Formats
        </button>
        <button
          onClick={() => setActiveMode('watch')}
          style={{
            flex: 1,
            minWidth: 120,
            padding: '.65rem .85rem',
            border: 'none',
            borderRadius: 12,
            fontWeight: 900,
            fontSize: '.83rem',
            cursor: 'pointer',
            background: activeMode === 'watch' ? 'linear-gradient(135deg, #ef4444, #dc2626)' : 'rgba(255,255,255,0.08)',
            color: '#fff',
            transition: 'all 0.2s'
          }}
        >
          📺 Watch Video
        </button>
        <button
          onClick={() => setActiveMode('read')}
          style={{
            flex: 1,
            minWidth: 120,
            padding: '.65rem .85rem',
            border: 'none',
            borderRadius: 12,
            fontWeight: 900,
            fontSize: '.83rem',
            cursor: 'pointer',
            background: activeMode === 'read' ? 'linear-gradient(135deg, #38bdf8, #0284c7)' : 'rgba(255,255,255,0.08)',
            color: '#fff',
            transition: 'all 0.2s'
          }}
        >
          📖 Read Notes
        </button>
        <button
          onClick={() => setActiveMode('revise')}
          style={{
            flex: 1,
            minWidth: 120,
            padding: '.65rem .85rem',
            border: 'none',
            borderRadius: 12,
            fontWeight: 900,
            fontSize: '.83rem',
            cursor: 'pointer',
            background: activeMode === 'revise' ? 'linear-gradient(135deg, #f59e0b, #d97706)' : 'rgba(255,255,255,0.08)',
            color: '#fff',
            transition: 'all 0.2s'
          }}
        >
          🎴 Revise Mind Map
        </button>
      </div>

      {/* Mode Details Banner */}
      {activeMode === 'revise' && (
        <div style={{ marginTop: '1rem', background: 'rgba(245,158,11,0.15)', border: '1px solid rgba(253,230,138,0.25)', borderRadius: 14, padding: '1rem', display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '.75rem' }}>
          <div>
            <div style={{ fontWeight: 800, color: '#fef08a', fontSize: '.9rem' }}>🎴 Revise &amp; Memorize Fast:</div>
            <div style={{ fontSize: '.82rem', color: 'rgba(255,255,255,0.85)', marginTop: '.1rem' }}>Open interactive flashcards or download the 1-page mind map cheat sheet.</div>
          </div>
          <div style={{ display: 'flex', gap: '.5rem' }}>
            {onOpenFlashcards && (
              <button onClick={onOpenFlashcards} className="btn btn-primary" style={{ fontSize: '.8rem', padding: '.45rem .95rem', borderRadius: 10 }}>
                🎴 Open Flashcards →
              </button>
            )}
            <button onClick={handleDownloadMindMap} className="btn btn-secondary" style={{ fontSize: '.8rem', padding: '.45rem .95rem', borderRadius: 10, background: '#fff', color: '#1e293b' }}>
              📥 Download 1-Page Mind Map
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
