const OFFLINE_KEY_PREFIX = 'osh_offline_topic_';

export function saveTopicOffline(topic, classId, subjectId) {
  try {
    const key = `${OFFLINE_KEY_PREFIX}${topic.id || topic.title.toLowerCase().replace(/\s+/g, '-')}`;
    const payload = {
      id: topic.id || topic.title.toLowerCase().replace(/\s+/g, '-'),
      title: topic.title,
      definition: topic.definition,
      content: topic.content,
      subtopics: topic.subtopics || [],
      qa: topic.qa || [],
      classId,
      subjectId,
      savedAt: new Date().toISOString()
    };
    localStorage.setItem(key, JSON.stringify(payload));
    return true;
  } catch (err) {
    console.error('Failed to save topic offline:', err);
    return false;
  }
}

export function removeTopicOffline(topicId) {
  try {
    const key = `${OFFLINE_KEY_PREFIX}${topicId}`;
    localStorage.removeItem(key);
    return true;
  } catch {
    return false;
  }
}

export function getOfflineTopics() {
  const topics = [];
  try {
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      if (key?.startsWith(OFFLINE_KEY_PREFIX)) {
        const item = JSON.parse(localStorage.getItem(key));
        if (item) topics.push(item);
      }
    }
  } catch (err) {
    console.error('Failed to load offline topics:', err);
  }
  return topics;
}

export function isTopicSavedOffline(topicId) {
  try {
    const key = `${OFFLINE_KEY_PREFIX}${topicId}`;
    return Boolean(localStorage.getItem(key));
  } catch {
    return false;
  }
}

export function downloadNotebookLMAudioPodcast(topic) {
  const text = `====================================================
ONLINESTUDYHUB NOTEBOOKLM AUDIO PODCAST SUMMARY
Topic: ${topic.title}
====================================================

🎙️ HOST A: Welcome to the OnlineStudyHub Audio Podcast! Today we are breaking down ${topic.title}.

🎙️ HOST B: That's right! Let's start with the fundamental definition:
"${topic.definition || 'Key concept principles and governing relations.'}"

🎙️ HOST A: How does this appear in ICSE/CBSE & Board Exams?
🎙️ HOST B: Let's review the top active recall PYQs:

${topic.qa?.map((q, i) => `[Question ${i + 1}]: ${q.q}\n[Answer]: ${q.a}\n`).join('\n') || ''}

🎙️ HOST A: Excellent! Remember to write down given parameters and check SI units for full marks.

====================================================
Generated by OnlineStudyHub — NotebookLM Audio Engine
`;

  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${topic.id || 'topic'}-notebooklm-audio-podcast.txt`;
  a.click();
  URL.revokeObjectURL(url);
}
